<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BlackSectorRanksTab</AssemblyName>
    <RootNamespace>BlackSectorRanksTab</RootNamespace>
    <GenerateDependencyFile>true</GenerateDependencyFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.374" />
    <Reference Include="RanksApi">
      <HintPath>lib/RanksApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
